server:
  grpc_server_max_concurrent_streams: 1000
  grpc_server_max_recv_msg_size: 104857600
  grpc_server_max_send_msg_size: 104857600
  http_listen_port: 9009

activity_tracker:
  filepath: ./active-query-tracker

common:
  storage:

blocks_storage:

compactor:
  data_dir: /tmp/mimir/compactor
  sharding_ring:
    kvstore:

distributor:
  pool:
    health_check_ingesters: true

ingester:
  ring:
    final_sleep: 0s
    kvstore:
    min_ready_duration: 0s
    num_tokens: 512
    replication_factor: 1

ingester_client:
  grpc_client_config:
    grpc_compression: gzip
    max_recv_msg_size: 104857600
    max_send_msg_size: 104857600

limits:
  ingestion_burst_size: 500000
  ingestion_rate: 250000
  
multitenancy_enabled: false